[phases.setup]
nixpkgs = ["nodejs", "coreutils", "openssl", "bash", "git"]

[phases.install]
cmds = [
  "cd Backend && npm install",
  "cd FrontEnd && npm install"
]

[phases.build]
cmds = [
  "cd FrontEnd && npm run build"
]

[start]
cmd = "cd Backend && npm start"
